spring.application.name=tradeApplication

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url = jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username = student
spring.datasource.password = chocolatefrog
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
# File Upload Configuration
# spring.servlet.multipart.enabled=true
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB
# spring.servlet.multipart.file-size-threshold=2KB

# Optional: Show more detailed logs
# logging.level.org.springframework.web=DEBUG
# logging.level.com.trade.tradeApplication=DEBUG

# spring.servlet.multipart.resolve-lazily=false

spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:uploads/,file:uploads/images/users/